# Generated by Django 2.1.10 on 2019-10-11 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_name', models.CharField(max_length=100, verbose_name='item name')),
                ('itm_description', models.CharField(max_length=2000, null=True, verbose_name='item description')),
                ('itm_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('itm_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('itm_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('itm_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itm_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('itmtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('itmtype_name', models.CharField(max_length=100, verbose_name='resource type')),
                ('itmtype_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('itmtype_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('itmtype_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('itmtype_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itmtype_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='itm_resource_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.ItemType', verbose_name='item type'),
        ),
    ]
