# Generated by Django 2.1.10 on 2019-10-11 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itm_resource_type',
            new_name='itm_item_type_fk',
        ),
    ]
