# Generated by Django 2.1.10 on 2019-10-11 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20191011_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itm_item_type_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.ItemType', verbose_name='item type fk'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='itmtype_name',
            field=models.CharField(max_length=100, verbose_name='item type name'),
        ),
    ]
