# Generated by Django 2.1.10 on 2019-10-07 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCodeType',
            fields=[
                ('cct_id', models.AutoField(primary_key=True, serialize=False)),
                ('cct_name', models.CharField(max_length=150, verbose_name='location name')),
                ('cct_description', models.CharField(max_length=2000, verbose_name='location description')),
                ('cct_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('cct_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('cct_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cct_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cct_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeUnitType',
            fields=[
                ('cut_id', models.AutoField(primary_key=True, serialize=False)),
                ('cut_name', models.CharField(max_length=150, verbose_name='location name')),
                ('cut_description', models.CharField(max_length=2000, verbose_name='location description')),
                ('cut_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('cut_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('cut_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cut_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=150, verbose_name='location name')),
                ('loc_description', models.CharField(max_length=2000, verbose_name='location description')),
                ('loc_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('loc_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('loc_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loc_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('prjsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('prjsts_name', models.CharField(max_length=150, verbose_name='location name')),
                ('prjsts_description', models.CharField(max_length=2000, verbose_name='location description')),
                ('prjsts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('prjsts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('prjsts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prjsts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prjsts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceStatus',
            fields=[
                ('ressts_id', models.AutoField(primary_key=True, serialize=False)),
                ('ressts_name', models.CharField(max_length=150, verbose_name='location name')),
                ('ressts_description', models.CharField(max_length=2000, verbose_name='location description')),
                ('ressts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ressts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('ressts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ressts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
