# Generated by Django 2.1.10 on 2019-10-08 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20191007_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListPriority',
            fields=[
                ('ltprty_id', models.AutoField(primary_key=True, serialize=False)),
                ('ltprty_name', models.CharField(max_length=150, verbose_name='list priority name')),
                ('ltprty_description', models.CharField(max_length=2000, verbose_name='list priority description')),
                ('ltprty_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ltprty_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('ltprty_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ltprty_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ltprty_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POItemType',
            fields=[
                ('poit_id', models.AutoField(primary_key=True, serialize=False)),
                ('poit_name', models.CharField(max_length=150, verbose_name='po item type name')),
                ('poit_description', models.CharField(max_length=2000, verbose_name='po item type description')),
                ('poit_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('poit_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('poit_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('poit_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poit_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RAGStatus',
            fields=[
                ('ragsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('ragsts_name', models.CharField(max_length=150, verbose_name='rag status name')),
                ('ragsts_description', models.CharField(max_length=2000, verbose_name='rag status description')),
                ('ragsts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ragsts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('ragsts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ragsts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ragsts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RAIDStatus',
            fields=[
                ('raidsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('raidsts_name', models.CharField(max_length=150, verbose_name='raid status name')),
                ('raidsts_description', models.CharField(max_length=2000, verbose_name='raid status description')),
                ('raidsts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('raidsts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('raidsts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('raidsts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raidsts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RAIDType',
            fields=[
                ('raidtyp_id', models.AutoField(primary_key=True, serialize=False)),
                ('raidtyp_name', models.CharField(max_length=150, verbose_name='raid type name')),
                ('raidtyp_description', models.CharField(max_length=2000, verbose_name='raid type description')),
                ('raidtyp_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('raidtyp_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('raidtyp_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('raidtyp_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raidtyp_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
