# Generated by Django 2.1.10 on 2019-11-06 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0004_hardwarecategory_hardwarestatus_softwarecategory_softwareclassification_softwarestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('prdtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('prdtype_name', models.CharField(max_length=150, verbose_name='product type name')),
                ('prdtype_description', models.CharField(max_length=2000, verbose_name='product type description')),
                ('prdtype_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('prdtype_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('prdtype_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prdtype_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prdtype_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
