# Generated by Django 2.1.10 on 2019-11-20 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0005_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalse',
            fields=[
                ('tf_id', models.AutoField(primary_key=True, serialize=False)),
                ('tf_text', models.CharField(max_length=10, verbose_name='yes no')),
                ('tf_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('tf_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('tf_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tf_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tf_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YesNo',
            fields=[
                ('yesno_id', models.AutoField(primary_key=True, serialize=False)),
                ('yesno_text', models.CharField(max_length=10, verbose_name='yes no')),
                ('yesno_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('yesno_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('yesno_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('yesno_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yesno_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
