# Generated by Django 2.1.10 on 2019-11-20 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0008_auto_20191120_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorFrequency',
            fields=[
                ('vendfreq_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendfreq_text', models.CharField(max_length=250, verbose_name='Vendor Release Frequency')),
                ('vendfreq_desc', models.CharField(blank=True, max_length=2500, null=True, verbose_name='Vendor Release Frequency Description')),
                ('vendfreq_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendfreq_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('vendfreq_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendfreq_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendfreq_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='approvalstatus',
            name='apprsts_desc',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Approval Status Description'),
        ),
        migrations.AddField(
            model_name='softwarefrequency',
            name='swfreq_desc',
            field=models.CharField(blank=True, max_length=2500, null=True, verbose_name='Agreed Release Frequency Description'),
        ),
        migrations.AlterField(
            model_name='softwarefrequency',
            name='swfreq_text',
            field=models.CharField(max_length=250, verbose_name='Agreed Release Frequency'),
        ),
    ]
