# Generated by Django 2.1.10 on 2019-12-11 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0009_auto_20191120_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListImpact',
            fields=[
                ('ltimpact_id', models.AutoField(primary_key=True, serialize=False)),
                ('ltimpact_name', models.CharField(max_length=150, verbose_name='list impact name')),
                ('ltimpact_score', models.IntegerField(max_length=2, verbose_name='list impact score')),
                ('ltimpact_description', models.CharField(max_length=2000, verbose_name='list impact description')),
                ('ltimpact_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ltimpact_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('ltimpact_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ltimpact_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ltimpact_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListSeverity',
            fields=[
                ('ltsev_id', models.AutoField(primary_key=True, serialize=False)),
                ('ltsev_name', models.CharField(max_length=150, verbose_name='list severity name')),
                ('ltsev_score', models.IntegerField(max_length=2, verbose_name='list severity score')),
                ('ltsev_description', models.CharField(max_length=2000, verbose_name='list severity description')),
                ('ltsev_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ltsev_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('ltsev_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ltsev_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ltsev_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListStatus',
            fields=[
                ('ltsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('ltsts_name', models.CharField(max_length=150, verbose_name='list status name')),
                ('ltsts_description', models.CharField(max_length=2000, verbose_name='list status description')),
                ('ltsts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ltsts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('ltsts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ltsts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ltsts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskImpact',
            fields=[
                ('rskimpact_id', models.AutoField(primary_key=True, serialize=False)),
                ('rskimpact_name', models.CharField(max_length=150, verbose_name='risk impact name')),
                ('rskimpact_score', models.IntegerField(max_length=2, verbose_name='risk impact score')),
                ('rskimpact_description', models.CharField(max_length=2000, verbose_name='risk impact description')),
                ('rskimpact_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('rskimpact_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('rskimpact_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rskimpact_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rskimpact_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskLikelihood',
            fields=[
                ('rsklklh_id', models.AutoField(primary_key=True, serialize=False)),
                ('rsklklh_name', models.CharField(max_length=150, verbose_name='risk likelihood name')),
                ('rsklklh_score', models.IntegerField(max_length=2, verbose_name='risk likelihood score')),
                ('rsklklh_description', models.CharField(max_length=2000, verbose_name='risk likelihood description')),
                ('rsklklh_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('rsklklh_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('rsklklh_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rsklklh_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsklklh_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
