# Generated by Django 2.1.10 on 2019-10-01 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('statustype', '0001_initial'),
        ('customers', '0002_auto_20190927_1210'),
        ('chgcodetype', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150, verbose_name='Project Name')),
                ('project_reference', models.CharField(max_length=255, verbose_name='Project Reference')),
                ('project_chargecode', models.CharField(max_length=255, verbose_name='Charge Code')),
                ('project_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_modifieddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_chargecodetype_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chgcodetype.ChgCodeType', verbose_name='Charge Code Type')),
                ('project_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project_customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Customer')),
                ('project_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prj_editor', to=settings.AUTH_USER_MODEL)),
                ('project_statustype_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statustype.StatusType', verbose_name='Status')),
            ],
        ),
    ]
