# Generated by Django 2.1.10 on 2019-09-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_chargecode',
            field=models.CharField(default='wbs', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_chargecodetype',
            field=models.CharField(choices=[('wbs', 'WBS Code'), ('ctr', 'Cost Centre'), ('trs', 'MARS Request')], default='wbs', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='project_reference',
            field=models.CharField(default='', max_length=255, verbose_name='Project Reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('onhold', 'On Hold'), ('archive', 'Archive')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_customer_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Customer'),
        ),
    ]
