# Generated by Django 2.1.10 on 2019-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190930_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_chargecode',
            field=models.CharField(max_length=255, verbose_name='Charge Code'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_chargecodetype',
            field=models.CharField(choices=[('wbs', 'WBS Code'), ('ctr', 'Cost Centre'), ('trs', 'MARS Request')], default='wbs', max_length=25, verbose_name='Charge Code Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('onhold', 'On Hold'), ('archive', 'Archive')], default='active', max_length=25, verbose_name='Status'),
        ),
    ]
