# Generated by Django 2.1.10 on 2019-09-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chgcodetype', '0001_initial'),
        ('projects', '0003_project_project_statustype_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_chargecodetype_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chgcodetype.ChgCodeType', verbose_name='Charge Code Type'),
        ),
    ]
