# Generated by Django 2.1.10 on 2019-10-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191007_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_chargecodetype_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chgcodetype.ChgCodeType', verbose_name='Charge Code Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_statustype_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statustype.StatusType', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectresources',
            name='pr_statustype_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='statustype.StatusType', verbose_name='res status'),
        ),
    ]
