# Generated by Django 2.1.10 on 2019-10-11 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customercontact_custcontact_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0003_listpriority_poitemtype_ragstatus_raidstatus_raidtype'),
        ('suppliers', '0001_initial'),
        ('items', '0001_initial'),
        ('projects', '0008_auto_20191008_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('prjcontact', models.AutoField(primary_key=True, serialize=False)),
                ('prjcontact_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('prjcontact_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('prjcontact_role', models.CharField(max_length=150, null=True, verbose_name='Role')),
                ('prjcontact_email', models.EmailField(max_length=250, verbose_name='Email Address')),
                ('prjcontact_telnum', models.CharField(max_length=150, verbose_name='Telephone Number')),
                ('prjcontact_mobnumber', models.CharField(max_length=150, verbose_name='Mobile Number')),
                ('prjcontact_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('prjcontact_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('prjcontact_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prjcontact_customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Customer')),
                ('prjcontact_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prjcontact_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectItems',
            fields=[
                ('pitm_id', models.AutoField(primary_key=True, serialize=False)),
                ('pitm_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pitm_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('pitm_chargeunit_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.ChargeUnitType', verbose_name='charge unit')),
                ('pitm_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pitm_customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='customer')),
                ('pitm_item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Item', verbose_name='Item')),
                ('pitm_location_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.Location', verbose_name='location')),
                ('pitm_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prjitm_editor', to=settings.AUTH_USER_MODEL)),
                ('pitm_project_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='project')),
                ('pitm_supplier_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Supplier', verbose_name='supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prjnote_note', models.CharField(max_length=2500, verbose_name='Note')),
                ('prjnote_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('prjnote_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('prjnote_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prjnote_customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Customer')),
                ('prjnote_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prjnote_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectresources',
            name='pr_createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectresources',
            name='pr_createddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='projectresources',
            name='pr_modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prjres_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectresources',
            name='pr_modifieddate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
