# Generated by Django 2.1.10 on 2019-11-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_auto_20191011_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('prjattach_id', models.AutoField(primary_key=True, serialize=False)),
                ('prjattach_title', models.CharField(max_length=2500, verbose_name='Attacment Title')),
                ('prjattach_file', models.FileField(max_length=255, upload_to='prjfiles/')),
                ('prjattach_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('prjattach_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('prjattach_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prjattach_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prjattach_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
