# Generated by Django 2.1.10 on 2019-09-30 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('svcarea', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svcelement_name', models.CharField(max_length=150, verbose_name='Service Area Name')),
                ('svcelement_description', models.CharField(max_length=2000, verbose_name='Description')),
                ('svcelement_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('svcelement_modifieddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('svcelement_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('svcelement_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='svcelement_editor', to=settings.AUTH_USER_MODEL)),
                ('svcelement_svcarea_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='svcarea.ServiceArea', verbose_name='Service Area')),
            ],
        ),
    ]
