# Generated by Django 2.1.10 on 2019-09-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svcelement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceelement',
            name='svcelement_name',
            field=models.CharField(max_length=150, verbose_name='Service Element Name'),
        ),
    ]
