# Generated by Django 2.1.10 on 2019-10-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svcelement', '0002_auto_20190930_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceelement',
            name='svcelement_modifieddate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
