# Generated by Django 2.1.10 on 2019-10-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20190927_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_modifieddate',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
