# Generated by Django 2.1.10 on 2019-10-02 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_auto_20191001_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custcontact_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('custcontact_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('custcontact_email', models.EmailField(max_length=250, verbose_name='Email Address')),
                ('custcontact_telnum', models.CharField(max_length=150, verbose_name='Telephone Number')),
                ('custcontact_mobnumber', models.CharField(max_length=150, verbose_name='Mobile Number')),
                ('custcontact_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('custcontact_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('custcontact_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custcontact_customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Customer')),
                ('custcontact_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custcontact_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custnote_note', models.CharField(max_length=2500, verbose_name='Note')),
                ('custnote_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('custnote_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('custnote_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custnote_customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Customer')),
                ('custnote_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custnote_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
