# Generated by Django 2.1.10 on 2019-10-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customercontact_customernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='custcontact_role',
            field=models.CharField(max_length=150, null=True, verbose_name='Role'),
        ),
    ]
