# Generated by Django 2.1.10 on 2019-10-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='res_networkid',
            field=models.CharField(default='', max_length=50, verbose_name='network id'),
            preserve_default=False,
        ),
    ]
