# Generated by Django 2.1.10 on 2019-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_res_networkid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='res_emp_ref',
            field=models.CharField(max_length=50, null=True, verbose_name='employee reference'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='res_networkid',
            field=models.CharField(max_length=50, null=True, verbose_name='network id'),
        ),
    ]
