# Generated by Django 2.1.10 on 2019-09-30 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChgCodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chgcodetype_name', models.CharField(max_length=150, verbose_name='Charge Code Type Name')),
                ('chgcodetype_description', models.CharField(max_length=2000, verbose_name='Description')),
                ('chgcodetype_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('chgcodetype_modifieddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('chgcodetype_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chgcodetype_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chgcodetype_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
