# Generated by Django 2.1.10 on 2019-09-30 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svcarea_name', models.CharField(max_length=150, verbose_name='Service Area Name')),
                ('svcarea_description', models.CharField(max_length=2000, verbose_name='Description')),
                ('svcarea_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('svcarea_modifieddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('svcarea_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('svcarea_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='svcarea_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
