# Generated by Django 2.1.10 on 2019-10-18 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_auto_20191011_1340'),
        ('customers', '0005_customercontact_custcontact_role'),
        ('suppliers', '0002_auto_20191011_1553'),
        ('lists', '0003_listpriority_poitemtype_ragstatus_raidstatus_raidtype'),
        ('approvers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purorders', '0002_purchaseorder_po_status_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='INVMatrix',
            fields=[
                ('invmtx_id', models.AutoField(primary_key=True, serialize=False)),
                ('invmtx_apprvd_date', models.DateField(null=True, verbose_name='approved date')),
                ('invmtx_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('invmtx_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('invmtx_approver_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvers.Approver', verbose_name='approver')),
                ('invmtx_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invmtx_customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='customer')),
            ],
        ),
        migrations.CreateModel(
            name='INVNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invnote_note', models.CharField(max_length=2500, verbose_name='Invoice Note')),
                ('invnote_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('invnote_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('invnote_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('inv_id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_reference', models.CharField(max_length=50, verbose_name='invoice reference')),
                ('inv_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='invoice quantity number')),
                ('inv_cost_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='invoice cost value')),
                ('inv_unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='invoice unit cost')),
                ('inv_date', models.DateField(null=True, verbose_name='Invoice Date')),
                ('inv_end_date', models.DateField(null=True, verbose_name='End Date')),
                ('inv_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('inv_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('inv_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inv_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inv_editor', to=settings.AUTH_USER_MODEL)),
                ('inv_quantity_type_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.ChargeUnitType', verbose_name='invoice quantity type')),
            ],
        ),
        migrations.CreateModel(
            name='INVStatus',
            fields=[
                ('invsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('invsts_name', models.CharField(max_length=150, verbose_name='invoice status name')),
                ('invsts_description', models.CharField(max_length=2000, verbose_name='invoice status description')),
                ('invsts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('invsts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('invsts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invsts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invsts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='INVType',
            fields=[
                ('invtyp_id', models.AutoField(primary_key=True, serialize=False)),
                ('invtyp_name', models.CharField(max_length=150, verbose_name='inv type name')),
                ('invtyp_description', models.CharField(max_length=2000, verbose_name='inv type description')),
                ('invtyp_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('invtyp_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('invtyp_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invtyp_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invtyp_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invnote',
            name='invnote_inv_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.Invoice', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='invnote',
            name='invnote_modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invnote_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invmatrix',
            name='invmtx_inv_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.Invoice', verbose_name='invoice'),
        ),
        migrations.AddField(
            model_name='invmatrix',
            name='invmtx_modifiedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invtx_editor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invmatrix',
            name='invmtx_po_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purorders.PurchaseOrder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='invmatrix',
            name='invmtx_project_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='invmatrix',
            name='invmtx_status_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.INVStatus', verbose_name='inv status'),
        ),
        migrations.AddField(
            model_name='invmatrix',
            name='invmtx_supplier_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Supplier', verbose_name='supplier'),
        ),
    ]
