# Generated by Django 2.1.10 on 2019-10-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='inv_end_date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='inv_gr_date',
            field=models.DateField(null=True, verbose_name='gr date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inv_gr_reference',
            field=models.CharField(max_length=50, null=True, verbose_name='invoice gr reference'),
        ),
    ]
