# Generated by Django 2.1.10 on 2020-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20200114_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='inv_cost_value_currency',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='inv_unit_cost_currency',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='inv_cost_value',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='inv_unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
