# Generated by Django 2.1.10 on 2020-01-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20200121_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inv_chg_value',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='inv_unit_chg',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
