# Generated by Django 2.1.10 on 2019-10-15 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approver',
            fields=[
                ('appr_id', models.AutoField(primary_key=True, serialize=False)),
                ('appr_firstname', models.CharField(max_length=100, verbose_name='firstname')),
                ('appr_lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('appr_role', models.CharField(max_length=150, null=True, verbose_name='role')),
                ('appr_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('appr_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('appr_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('appr_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appr_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
