# Generated by Django 2.1.10 on 2019-09-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statustype',
            name='statustype_name',
            field=models.CharField(max_length=150, verbose_name='Status Type Name'),
        ),
    ]
