# Generated by Django 2.1.10 on 2019-10-08 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supp_id', models.AutoField(primary_key=True, serialize=False)),
                ('supp_name', models.CharField(max_length=150, verbose_name='supplier name')),
                ('supp_description', models.CharField(max_length=2000, verbose_name='supplier description')),
                ('supp_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('supp_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('supp_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supp_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supp_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
