# Generated by Django 2.1.10 on 2019-10-11 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppcontact_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('suppcontact_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('suppcontact_role', models.CharField(max_length=150, null=True, verbose_name='Role')),
                ('suppcontact_email', models.EmailField(max_length=250, verbose_name='Email Address')),
                ('suppcontact_telnum', models.CharField(max_length=150, verbose_name='Telephone Number')),
                ('suppcontact_mobnumber', models.CharField(max_length=150, verbose_name='Mobile Number')),
                ('suppcontact_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('suppcontact_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('suppcontact_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suppcontact_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppcontact_editor', to=settings.AUTH_USER_MODEL)),
                ('suppcontact_supplier_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Supplier', verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppnote_note', models.CharField(max_length=2500, verbose_name='Note')),
                ('suppnote_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('suppnote_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('suppnote_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suppnote_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppnote_editor', to=settings.AUTH_USER_MODEL)),
                ('suppnote_supplier_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Supplier', verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierStatus',
            fields=[
                ('suppsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('suppsts_name', models.CharField(max_length=150, verbose_name='supplier status name')),
                ('suppsts_description', models.CharField(max_length=2000, verbose_name='supplier status description')),
                ('suppsts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('suppsts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('suppsts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('suppsts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppsts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='supplier',
            name='supp_status_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.SupplierStatus', verbose_name='supplier status'),
        ),
    ]
