# Generated by Django 2.1.10 on 2019-10-15 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvers', '0001_initial'),
        ('suppliers', '0002_auto_20191011_1553'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0003_listpriority_poitemtype_ragstatus_raidstatus_raidtype'),
        ('projects', '0009_auto_20191011_1340'),
        ('customers', '0005_customercontact_custcontact_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='POMatrix',
            fields=[
                ('pomtx_id', models.AutoField(primary_key=True, serialize=False)),
                ('pomtx_apprvd_date', models.DateField(null=True, verbose_name='approved date')),
                ('pomtx_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pomtx_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('pomtx_approver_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approvers.Approver', verbose_name='approver')),
                ('pomtx_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pomtx_customer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='customer')),
                ('pomtx_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomtx_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PONote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponote_note', models.CharField(max_length=2500, verbose_name='PO Note')),
                ('ponote_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ponote_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('ponote_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ponote_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponote_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POStatus',
            fields=[
                ('posts_id', models.AutoField(primary_key=True, serialize=False)),
                ('posts_name', models.CharField(max_length=150, verbose_name='po status name')),
                ('posts_description', models.CharField(max_length=2000, verbose_name='po status description')),
                ('posts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('posts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('posts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('posts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POType',
            fields=[
                ('potyp_id', models.AutoField(primary_key=True, serialize=False)),
                ('potyp_name', models.CharField(max_length=150, verbose_name='po type name')),
                ('potyp_description', models.CharField(max_length=2000, verbose_name='po type description')),
                ('potyp_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('potyp_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('potyp_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('potyp_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='potyp_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.AutoField(primary_key=True, serialize=False)),
                ('po_reference', models.CharField(max_length=50, verbose_name='po reference')),
                ('po_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='po quantity number')),
                ('po_cost_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='po cost value')),
                ('po_unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='po unit cost')),
                ('po_charge_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='po charge value')),
                ('po_unit_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='po unit charge')),
                ('po_start_date', models.DateField(null=True, verbose_name='Start Date')),
                ('po_end_date', models.DateField(null=True, verbose_name='End Date')),
                ('po_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('po_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('po_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('po_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_editor', to=settings.AUTH_USER_MODEL)),
                ('po_quantity_type_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.ChargeUnitType', verbose_name='po quantity type')),
            ],
        ),
        migrations.AddField(
            model_name='ponote',
            name='ponote_po_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purorders.PurchaseOrder', verbose_name='Purchase Order'),
        ),
        migrations.AddField(
            model_name='pomatrix',
            name='pomtx_po_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purorders.PurchaseOrder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='pomatrix',
            name='pomtx_project_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='pomatrix',
            name='pomtx_status_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purorders.POStatus', verbose_name='po status'),
        ),
        migrations.AddField(
            model_name='pomatrix',
            name='pomtx_supplier_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.Supplier', verbose_name='supplier'),
        ),
    ]
