# Generated by Django 2.1.10 on 2019-10-22 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purorders', '0002_purchaseorder_po_status_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomatrix',
            name='pomtx_potype_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purorders.POType', verbose_name='purchase order type'),
        ),
    ]
