# Generated by Django 2.1.10 on 2019-10-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purorders', '0003_pomatrix_pomtx_potype_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='POFiles',
            fields=[
                ('pofile_id', models.AutoField(primary_key=True, serialize=False)),
                ('pofile_name', models.CharField(max_length=255, verbose_name='PO Filename')),
                ('pofile_file', models.FileField(max_length=255, upload_to='pofiles/')),
                ('pofile_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('pofile_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('pofile_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pofile_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pofile_editor', to=settings.AUTH_USER_MODEL)),
                ('pofile_po_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purorders.PurchaseOrder', verbose_name='Purchase Order')),
            ],
        ),
    ]
