# Generated by Django 2.1.10 on 2020-01-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purorders', '0006_auto_20200114_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_charge_value_currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_cost_value_currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_unit_charge_currency',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='po_unit_cost_currency',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_charge_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_cost_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='PO Quantity Number'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_quantity_type_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.ChargeUnitType', verbose_name='PO Quantity Type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_reference',
            field=models.CharField(max_length=50, verbose_name='PO Reference'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_unit_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
