# Generated by Django 2.1.10 on 2020-01-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purorders', '0008_auto_20200115_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='PO Unit Cost'),
        ),
    ]
