# Generated by Django 2.1.10 on 2020-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purorders', '0010_auto_20200116_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
