# Generated by Django 2.1.10 on 2019-11-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_truefalse_yesno'),
        ('software', '0002_auto_20191111_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='sw_see_txt',
        ),
        migrations.AddField(
            model_name='software',
            name='sw_see_yn_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.YesNo', verbose_name='Support End Estimated'),
        ),
    ]
