# Generated by Django 2.1.10 on 2019-11-20 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0007_approvalstatus_softwarefrequency'),
        ('software', '0003_auto_20191120_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWPortfolioCategory',
            fields=[
                ('swportcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('swportcat_name', models.CharField(max_length=150, verbose_name='SW Portfolio Status Name')),
                ('swportcat_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('swportcat_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('swportcat_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('swportcat_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swportcat_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='software',
            name='sw_latestver_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Latest Available Version'),
        ),
        migrations.AddField(
            model_name='software',
            name='sw_progver_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Version In Progress'),
        ),
        migrations.AddField(
            model_name='software',
            name='sw_swclass_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.SoftwareClassification', verbose_name='Software Classification'),
        ),
        migrations.AlterField(
            model_name='software',
            name='sw_portsts_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.SWPortfolioStatus', verbose_name='Portfolio Status'),
        ),
        migrations.AddField(
            model_name='software',
            name='sw_portcat_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.SWPortfolioCategory', verbose_name='Portfolio Category'),
        ),
    ]
