# Generated by Django 2.1.10 on 2019-11-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0004_auto_20191120_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='sw_eol_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Sale'),
        ),
    ]
