# Generated by Django 2.1.10 on 2019-11-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20191120_1733'),
        ('software', '0005_auto_20191120_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='sw_cust_notified',
            field=models.DateField(blank=True, null=True, verbose_name='Customer Notified'),
        ),
        migrations.AddField(
            model_name='software',
            name='sw_cust_ref',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer Reference'),
        ),
        migrations.AddField(
            model_name='software',
            name='sw_repl_ver',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Replacement Software Version'),
        ),
        migrations.AddField(
            model_name='software',
            name='sw_swfreq_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.SoftwareFrequency', verbose_name='Software Release Frequency'),
        ),
        migrations.AddField(
            model_name='software',
            name='sw_vendfreq_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.VendorFrequency', verbose_name='Vendor Release Frequency'),
        ),
        migrations.AddField(
            model_name='software',
            name='sw_version',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Software Version'),
        ),
        migrations.AlterField(
            model_name='software',
            name='sw_eol_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Life'),
        ),
    ]
