# Generated by Django 2.1.10 on 2019-11-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0007_softwarevendor_swvendorcontact_swvendornote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='sw_see_yn_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.YesNo', verbose_name='Is SEE'),
        ),
    ]
