# Generated by Django 2.1.10 on 2019-11-22 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('software', '0009_auto_20191121_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareMatrix',
            fields=[
                ('swmtx_id', models.AutoField(primary_key=True, serialize=False)),
                ('swmtx_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('swmtx_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('swmtx_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('swmtx_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swmtx_editor', to=settings.AUTH_USER_MODEL)),
                ('swmtx_sw_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.Software', verbose_name='Software')),
                ('swmtx_swvend_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.SoftwareVendor', verbose_name='Software Vendor')),
            ],
        ),
    ]
