# Generated by Django 2.1.10 on 2019-11-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_auto_20191120_1733'),
        ('software', '0011_auto_20191122_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarematrix',
            name='swmtx_cust_ref',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer Reference'),
        ),
        migrations.AddField(
            model_name='softwarematrix',
            name='swmtx_portcat_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.SWPortfolioCategory', verbose_name='Portfolio Category'),
        ),
        migrations.AddField(
            model_name='softwarematrix',
            name='swmtx_portsts_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.SWPortfolioStatus', verbose_name='Portfolio Status'),
        ),
        migrations.AddField(
            model_name='softwarematrix',
            name='swmtx_swcat_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.SoftwareCategory', verbose_name='Software Category'),
        ),
        migrations.AddField(
            model_name='softwarematrix',
            name='swmtx_swclass_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.SoftwareClassification', verbose_name='Software Classification'),
        ),
        migrations.AddField(
            model_name='softwarematrix',
            name='swmtx_swsts_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.SoftwareStatus', verbose_name='Software Status'),
        ),
        migrations.AlterField(
            model_name='softwarematrix',
            name='swmtx_cust_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Software Customer'),
        ),
        migrations.AlterField(
            model_name='softwarematrix',
            name='swmtx_sw_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='software.Software', verbose_name='Software Product'),
        ),
    ]
