# Generated by Django 2.1.10 on 2019-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0013_auto_20191122_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='sw_suppeol_txt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Supplier End of Life Policy'),
        ),
    ]
