# Generated by Django 2.1.10 on 2019-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0014_software_sw_suppeol_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwarematrix',
            name='swmtx_cust_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer Reference'),
        ),
    ]
