# Generated by Django 2.1.10 on 2019-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0015_softwarematrix_swmtx_cust_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softwarematrix',
            name='swmtx_cust_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer Code'),
        ),
    ]
