# Generated by Django 2.1.10 on 2019-11-06 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vend_id', models.AutoField(primary_key=True, serialize=False)),
                ('vend_name', models.CharField(max_length=150, verbose_name='Vendor Name')),
                ('vend_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('vend_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('vend_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vend_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vend_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('vendcontact_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendcontact_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('vendcontact_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('vendcontact_role', models.CharField(max_length=150, null=True, verbose_name='Role')),
                ('vendcontact_email', models.EmailField(max_length=250, verbose_name='Email Address')),
                ('vendcontact_telnum', models.CharField(max_length=150, verbose_name='Telephone Number')),
                ('vendcontact_mobnumber', models.CharField(max_length=150, verbose_name='Mobile Number')),
                ('vendcontact_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendcontact_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('vendcontact_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendcontact_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendcontact_editor', to=settings.AUTH_USER_MODEL)),
                ('vendcontact_vendor_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorNote',
            fields=[
                ('vendnote_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendnote_note', models.CharField(max_length=2500, verbose_name='Note')),
                ('vendnote_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendnote_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('vendnote_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendnote_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendnote_editor', to=settings.AUTH_USER_MODEL)),
                ('vendnote_vendomer_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vendor', verbose_name='Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorType',
            fields=[
                ('vendtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendtype_name', models.CharField(max_length=150, verbose_name='Vendor Type Name')),
                ('vendtype_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('vendtype_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('vendtype_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendtype_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendtype_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vendor',
            name='vend_type_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.VendorType', verbose_name='Vendor Type'),
        ),
    ]
