# Generated by Django 2.1.10 on 2019-11-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20191111_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendornote',
            old_name='vendnote_vendomer_fk',
            new_name='vendnote_vend_fk',
        ),
    ]
