# Generated by Django 2.1.10 on 2019-11-06 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_customercontact_custcontact_role'),
        ('lists', '0004_hardwarecategory_hardwarestatus_softwarecategory_softwareclassification_softwarestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('hw_id', models.AutoField(primary_key=True, serialize=False)),
                ('hw_description', models.CharField(max_length=250, verbose_name='Hardware Description')),
                ('hw_int_code', models.CharField(max_length=250, verbose_name='Internal Part Code')),
                ('hw_ext_code', models.CharField(max_length=250, verbose_name='External Part Code')),
                ('hw_eol_date', models.DateTimeField(null=True)),
                ('hw_upd_date', models.DateTimeField(null=True)),
                ('hw_int_reference', models.CharField(max_length=250, verbose_name='Internal Reference')),
                ('hw_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('hw_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('hw_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hw_cust_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer')),
                ('hw_hwcat_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.HardwareCategory')),
                ('hw_hwsts_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.HardwareStatus')),
                ('hw_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareContact',
            fields=[
                ('hwcontact_id', models.AutoField(primary_key=True, serialize=False)),
                ('hwcontact_firstname', models.CharField(max_length=150, verbose_name='First Name')),
                ('hwcontact_lastname', models.CharField(max_length=150, verbose_name='Last Name')),
                ('hwcontact_role', models.CharField(max_length=150, null=True, verbose_name='Role')),
                ('hwcontact_email', models.EmailField(max_length=250, verbose_name='Email Address')),
                ('hwcontact_telnum', models.CharField(max_length=150, verbose_name='Telephone Number')),
                ('hwcontact_mobnumber', models.CharField(max_length=150, verbose_name='Mobile Number')),
                ('hwcontact_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('hwcontact_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('hwcontact_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hwcontact_hw_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.Hardware', verbose_name='Hardware')),
                ('hwcontact_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hwcontact_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareNote',
            fields=[
                ('hwnote_id', models.AutoField(primary_key=True, serialize=False)),
                ('hwnote_note', models.CharField(max_length=2500, verbose_name='Note')),
                ('hwnote_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('hwnote_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('hwnote_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hwnote_hw_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.Hardware', verbose_name='Hardware')),
                ('hwnote_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hwnote_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioStatus',
            fields=[
                ('portsts_id', models.AutoField(primary_key=True, serialize=False)),
                ('portsts_name', models.CharField(max_length=150, verbose_name='Portfolio Status Name')),
                ('portsts_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('portsts_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('portsts_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portsts_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portsts_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='hardware',
            name='hw_portsts_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.PortfolioStatus'),
        ),
    ]
