# Generated by Django 2.1.10 on 2019-11-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_auto_20191106_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='hw_ees1_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_ees2_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_ees3_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_ems_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_eol_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_eow_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_upd_date',
            field=models.DateField(null=True),
        ),
    ]
