# Generated by Django 2.1.10 on 2019-11-07 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_auto_20191107_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='hw_createdby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_cust_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_ees1_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Extended Support - Period One'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_ees2_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Extended Support - Period Two'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_ees3_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Extended Support - Period Three'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_ems_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Mainstream Support'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_eol_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Life'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_eow_date',
            field=models.DateField(blank=True, null=True, verbose_name='End of Warranty'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_hwcat_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.HardwareCategory', verbose_name='Hardware Category'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_hwsts_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.HardwareStatus', verbose_name='Hardware Status'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_modifiedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_editor', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_portsts_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.PortfolioStatus', verbose_name='Portfolio Status'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_repl_vend_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hw_repl_vend_id', to='vendors.Vendor', verbose_name='Replacement Vendor'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_upd_date',
            field=models.DateField(blank=True, null=True, verbose_name='Info Update'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='hw_vend_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.Vendor', verbose_name='Vendor'),
        ),
    ]
