# Generated by Django 2.1.10 on 2019-12-02 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_customercontact_custcontact_role'),
        ('lists', '0009_auto_20191120_1733'),
        ('hardware', '0006_hardware_hw_see_yn_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareMatrix',
            fields=[
                ('hwmtx_id', models.AutoField(primary_key=True, serialize=False)),
                ('hwmtx_cust_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer Part Code')),
                ('hwmtx_cust_ref', models.CharField(blank=True, max_length=250, null=True, verbose_name='Customer Reference')),
                ('hwmtx_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('hwmtx_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('hwmtx_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hwmtx_cust_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.Customer', verbose_name='Software Customer')),
                ('hwmtx_hw_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.Hardware', verbose_name='Hardware Product')),
                ('hwmtx_hwcat_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.HardwareCategory', verbose_name='Hardware Category')),
                ('hwmtx_hwsts_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.HardwareStatus', verbose_name='Hardware Status')),
                ('hwmtx_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hwmtx_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('portcat_id', models.AutoField(primary_key=True, serialize=False)),
                ('portcat_name', models.CharField(max_length=250, verbose_name='Portfolio Category Name')),
                ('portcat_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('portcat_modifieddate', models.DateTimeField(auto_now=True, null=True)),
                ('portcat_createdby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portcat_modifiedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portcat_editor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='portfoliostatus',
            name='portsts_name',
            field=models.CharField(max_length=250, verbose_name='Portfolio Status Name'),
        ),
        migrations.AddField(
            model_name='hardwarematrix',
            name='hwmtx_portcat_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.PortfolioCategory', verbose_name='Portfolio Category'),
        ),
        migrations.AddField(
            model_name='hardwarematrix',
            name='hwmtx_portsts_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hardware.PortfolioStatus', verbose_name='Portfolio Status'),
        ),
    ]
