# Generated by Django 2.1.10 on 2019-11-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0006_auto_20191119_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='hw_see_txt',
            field=models.CharField(blank=True, default='No', max_length=10, null=True, verbose_name='Support End Estimated'),
        ),
    ]
