# Generated by Django 2.1.10 on 2019-11-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0008_auto_20191120_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='hw_see_txt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.YesNo', verbose_name='Support End Estimated'),
        ),
    ]
